# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(120E1A)
$foreground = rgb(F5F0FD)
$color0 = rgb(3A3743)
$color1 = rgb(9B39AE)
$color2 = rgb(B351B8)
$color3 = rgb(8C89B3)
$color4 = rgb(70ABBA)
$color5 = rgb(B79AB8)
$color6 = rgb(AAA0BA)
$color7 = rgb(E8E2F3)
$color8 = rgb(A29EAA)
$color9 = rgb(CE4CE8)
$color10 = rgb(EF6CF6)
$color11 = rgb(BBB7EF)
$color12 = rgb(96E3F8)
$color13 = rgb(F3CDF6)
$color14 = rgb(E2D5F9)
$color15 = rgb(E8E2F3)
