# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(201F23)
$foreground = rgb(E0F1F3)
$color0 = rgb(46454A)
$color1 = rgb(576C57)
$color2 = rgb(985662)
$color3 = rgb(826351)
$color4 = rgb(92745D)
$color5 = rgb(8A7F8C)
$color6 = rgb(7EA2A5)
$color7 = rgb(CBE3E5)
$color8 = rgb(8E9FA0)
$color9 = rgb(748F74)
$color10 = rgb(CB7383)
$color11 = rgb(AE856C)
$color12 = rgb(C39B7C)
$color13 = rgb(B8AABB)
$color14 = rgb(A7D8DC)
$color15 = rgb(CBE3E5)



# $background = rgb(241E30)
# $foreground = rgb(CFE9FC)
# $color0 = rgb(4B4458)
# $color1 = rgb(1B2C6D)
# $color2 = rgb(512898)
# $color3 = rgb(35568C)
# $color4 = rgb(923DAC)
# $color5 = rgb(5488B2)
# $color6 = rgb(5990B8)
# $color7 = rgb(B2D7F2)
# $color8 = rgb(7D97A9)
# $color9 = rgb(253B91)
# $color10 = rgb(6C35CA)
# $color11 = rgb(4772BB)
# $color12 = rgb(C351E5)
# $color13 = rgb(70B5ED)
# $color14 = rgb(77C0F5)
# $color15 = rgb(B2D7F2)
