# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts
$lock = $scriptsDir/LockScreen.sh
$SwwwRandom = $UserScripts/WallpaperAutoChange.sh
$livewallpaper=""
$wallDIR = $HOME/Pictures/wallpapers  # change path manually here if needed


# xdg-desktop-portal-hyprland (should be auto starting. However, you can force to start)
# exec-once = $scriptsDir/PortalFix.sh
exec-once = $scriptsDir/PortalHyprland.sh

# Cursor
exec-once=hyprctl setcursor Bibata-Modern-Classic 24
exec-once=gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic'
